version: "3"
services:
  server:
    container_name: backend
    build: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=viotdb
      - PGHOST=db # NAME OF THE SERVICE
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: "viot_pg"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=viotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: {}